# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dc20b01af51b8ad01c5c2a8796e329df2abb9f72bb988e75f15944df7d23dd27a84953e77bb3d51261076a54f6bf24bc495f08f0daff1f2083d7d2a10600bd9

test:
  secret_key_base: a9ef0da7eb4ce9c32c4102a8e5f5d2bde723f7677c644fa99a11bdb8a2c09fa25c0313df45eafae5c37715d27079566254c093904f3c4190bfd07862f0035feb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
